// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/case-file-chat/CalmConversation.tsx": () => import("../components/mockups/case-file-chat/CalmConversation.tsx"),
  "./components/mockups/case-file-chat/ClinicalTimeline.tsx": () => import("../components/mockups/case-file-chat/ClinicalTimeline.tsx"),
  "./components/mockups/case-file-chat/Current.tsx": () => import("../components/mockups/case-file-chat/Current.tsx")
};
