const colors = {
  light: {
    text: "#2A2A2A",
    tint: "#DB2841",
    background: "#F7F7F9",
    foreground: "#2A2A2A",
    card: "#FFFFFF",
    cardForeground: "#2A2A2A",
    primary: "#DB2841",
    primaryForeground: "#FFFFFF",
    secondary: "#ECEDF0",
    secondaryForeground: "#2A2A2A",
    muted: "#ECEDF0",
    mutedForeground: "#7A7F8A",
    accent: "#F0F1F4",
    accentForeground: "#2A2A2A",
    destructive: "#DB2841",
    destructiveForeground: "#FFFFFF",
    border: "#ECEDF0",
    input: "#ECEDF0",
    ring: "#DB2841",
    success: "#17A672",
    successForeground: "#FFFFFF",
    warning: "#E08A2E",
    warningForeground: "#FFFFFF",
    blue: "#2F6FED",
    terminal: "#9AA0AC",
    quiet: "#8C5B6E",
  },
  dark: {
    text: "#F2F2F2",
    tint: "#F05A6D",
    background: "#17181C",
    foreground: "#F2F2F2",
    card: "#23252B",
    cardForeground: "#F2F2F2",
    primary: "#F05A6D",
    primaryForeground: "#FFFFFF",
    secondary: "#30323A",
    secondaryForeground: "#F2F2F2",
    muted: "#30323A",
    mutedForeground: "#B7BBC4",
    accent: "#353740",
    accentForeground: "#F2F2F2",
    destructive: "#F05A6D",
    destructiveForeground: "#FFFFFF",
    border: "#3B3E47",
    input: "#3B3E47",
    ring: "#F05A6D",
    success: "#31C58F",
    successForeground: "#FFFFFF",
    warning: "#F0A34E",
    warningForeground: "#FFFFFF",
    blue: "#6E9BFF",
    terminal: "#9AA0AC",
    quiet: "#C38DA5",
  },
  radius: 12,
};

export default colors;
