import { designTokens } from "./designTokens";

const colors = {
  light: {
    text: designTokens.color.ink,
    tint: designTokens.color.coral,
    background: designTokens.color.canvas,
    foreground: designTokens.color.ink,
    card: designTokens.color.card,
    cardForeground: designTokens.color.ink,
    primary: designTokens.color.coral,
    primaryForeground: "#FFFFFF",
    secondary: "#F5E8E2",
    secondaryForeground: designTokens.color.ink,
    muted: "#F4E8E3",
    mutedForeground: designTokens.color.inkSoft,
    accent: designTokens.color.coralTint,
    accentForeground: designTokens.color.ink,
    destructive: designTokens.color.red,
    destructiveForeground: "#FFFFFF",
    border: designTokens.color.border,
    input: "#F2E5DF",
    ring: designTokens.color.coral,
    success: designTokens.color.green,
    successForeground: "#FFFFFF",
    warning: designTokens.color.gold,
    warningForeground: "#FFFFFF",
    blue: designTokens.color.blue,
    terminal: designTokens.color.terminal,
    quiet: designTokens.color.plum,
    conversationBackground: designTokens.color.canvas,
    conversationCard: designTokens.color.card,
    conversationPrimary: designTokens.color.coral,
    conversationPrimaryForeground: "#FFFFFF",
    conversationSoft: "#F8ECE7",
    conversationBorder: designTokens.color.border,
    conversationMuted: designTokens.color.inkSoft,
    advisoryBackground: designTokens.color.goldTint,
    advisoryBorder: "#D9BE98",
    advisoryForeground: "#785729",
    callBackground: designTokens.color.plumDark,
    callForeground: "#FFFFFF",
  },
  dark: {
    text: "#FDF6F1",
    tint: "#F27A62",
    background: "#241B1C",
    foreground: "#FDF6F1",
    card: "#302526",
    cardForeground: "#FDF6F1",
    primary: "#F27A62",
    primaryForeground: "#FFFFFF",
    secondary: "#3A2C2D",
    secondaryForeground: "#FDF6F1",
    muted: "#382A2B",
    mutedForeground: "#C5B1AA",
    accent: "#443031",
    accentForeground: "#FDF6F1",
    destructive: "#F07669",
    destructiveForeground: "#FFFFFF",
    border: "#4C3A3A",
    input: "#4C3A3A",
    ring: "#F27A62",
    success: "#3CC583",
    successForeground: "#FFFFFF",
    warning: "#D5A14D",
    warningForeground: "#FFFFFF",
    blue: "#8AA8E1",
    terminal: "#A99A94",
    quiet: "#D8A5B9",
    conversationBackground: "#241B1C",
    conversationCard: "#302526",
    conversationPrimary: "#F27A62",
    conversationPrimaryForeground: "#FFFFFF",
    conversationSoft: "#3A2C2D",
    conversationBorder: "#4C3A3A",
    conversationMuted: "#C5B1AA",
    advisoryBackground: "#3B3024",
    advisoryBorder: "#7E6547",
    advisoryForeground: "#E2B878",
    callBackground: "#1E1219",
    callForeground: "#FDF6F1",
  },
  radius: 12,
};

export default colors;
